# Generated by Django 3.0.5 on 2020-05-10 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200429_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='id',
        ),
        migrations.AddField(
            model_name='airport',
            name='city_code',
            field=models.CharField(default='XXX', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='continent_code',
            field=models.CharField(default='XXX', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='image_load',
            field=models.ImageField(blank=True, null=True, upload_to='images/media/', verbose_name='dodaj zdjęcie'),
        ),
    ]
