# Generated by Django 3.0.5 on 2020-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200510_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
    ]
