# Generated by Django 3.0.5 on 2020-05-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200510_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='airline_name',
            field=models.CharField(max_length=270),
        ),
    ]
