# Generated by Django 3.0.5 on 2020-05-11 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200511_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='votes_total',
            new_name='votes_minus',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_airport',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrivall_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrive', to='products.Airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrive_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='depart_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='scoring',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='flight',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='votes_plus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Airline'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart', to='products.Airport'),
        ),
    ]
